sudo: required
services: docker
language: bash
branches:
  only:
  - master
before_script:
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
script:
- "./build.sh"
after_success:
- "./push.sh"
notifications:
  slack:
    rooms:
      secure: oZaDKdpLHKe2gvEVl7gS9txnMqOq98VGiGvfTpZQfTGyyH4/JO6HnpupPGLPNW1TyjseoapH/mAJF+ibQZXyMKY50SxYPrhjaxaKtqKzVH97cWa6kHMQ6KxipVtYmHLJZLz8qVapXjYylvCL7BwtfJ7yU54L1DsyGhbp43TbXGHHHHvZpiahR4vxaHZP+yW8qmCBugESCg6mEI7xS8T1VBE2MOw/qaPOGfOuX69VlEAjavTHCihUyg5VbQCMtSolSKfeqDk+OhnoXVBFJXDeQRyY8XNYCcGrj28Gm/snBvIMrEwbNC5hcxKUC6pMkkdNyJtMSCia0GhiGBy7CTf/0tQVjObkpO4Y1GBQP466QpJU67R09xZKb0VOH5u8zQJeHS+ZoJ8zL0sPhoODC8l+eTaNSWKxOzqcdPAYAJ1PfQm/ljZwKSN32YaPbu/imBBqTaY5vzbw/6pktCawEMO/kbEmhxxLajeP6MqAMVBrU0M9AaFQ1gfcSFJXRbPmRF4qTCPtZzQpbi2df4UzfFSdUj5sWN0F+iM+ioTCSknHbmnmpRSRYugdNxfzZIcS8Ju6tBfB1adKUQMQvXeI+ABPqx0Z+yq3A95C+fhCfS6ExfTYupLHZ8bgwW5von6gxu+zDa6YyOLhuRnXY87FE0Qs3W3eFQrVaFecP210kSbca3g=
