sudo: required
services: docker
language: bash
branches:
  only:
  - master
before_script:
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
script:
- "./build.sh"
after_success:
- "./push.sh"
notifications:
  slack:
    rooms:
      secure: dMzA3Zd78X0BkqtL9F9m0RN6up9otYUyjBp21c6teZl2wx0rZi3N2TJV4Si8kJeLPxx4X4hgcniqv4Til6eb81nFyPUxykkcwsJMd/jO/rqC/Ja3AX87gxfZRde4sMD80R5NPIXo4fLHWzoV/L791LTjEWAwLVUezXU7gp31/DYOmFPYsWfz9PY66lYUvSOsZ+P+kje4gMI8iEq2BoMLqdaqaXsPsRIkIjohBJfEZ/Mr7wx5DL1urTNEVI8//ELTYKHINVND6u78/Ym9P6zuMBI4g42XCRxHbBFvw1p0jocGNnnSA6kICC4q1CNBzfaPXOu9MHM55K8E/ep+JI/uJuf0I6N5vSjbNrJa6JnMP8dlxCiyZ04ifOl6Koq7bY/9hwdj8Igp1RYQBeGxddTNpAhdwtpeFPQKRjn/8J/CpD7cnhls0OG/k2vEQuR9J2KTY0T3rO8qhX6Yf3y7zgc18b9o6ztVANxIT1LvugtTKDd4wGLyD+ota33qGJIPaY5B1FCE40OBnyAOBuXxYiSuR0gifU0URMrAnmVRa+omqauDWhXe90qOOXOUEAdi7EB+NCHMal+k+kcFVzDUt3bjr3ioqUNU9fLEFqM7jogujAqL2V5ZgDF59PGnROk/umygymHQDpUSqiJY4eMF5BTkBARv6+b5YyRLblo3GcG2A+4=
